### ISSUE TITLE
Presettings not working as they are supposed to

### ISSUE THREAD

**Issue by larsupb** [hschneid/xfvrp#41]
Implementation of presettings seems to be buggy. For demonstration, I've added a new test instance in branch "test_instances". Just try my test test_presets_and_timewindows(). However, resulting tours seem not to be optimized and time window constraints are violated.

**Comment by HolgerSchneider** [comment]
Awesome test case. This helps a lot!

**Comment by HolgerSchneider** [comment]
I checked and I can see, that you used the block feature very extensively.

Idea of block feature was, that "certain" nodes must be packed on one route, because they belong together from a business point of view: "If I unload at B, then loading at A must be done as well." The ordering of customers in a block is not specified directly.

But in your case, you put more than 5 customers in one block. Then the ordering becomes a critical problem, as certain blocks may have invalid orderings. So the Solution Builder tries to create a feasible solution for each block, but the creator is not so high optimized like the later optimization routines. So it fails to create a reasonable order of customers in a block.

If you want to inject a predefined sub-solution, where the optimization uses the existing and adds more stuff, then better use XFVRP.getParameter().setPredefinedSolutionString().

If you really want, that a certain route is fixated during an optimization, then use blocks AND presetPosition. In your example:
* CUSTOMER_100008= {block="67", pos=1}
* CUSTOMER_100088= {block="67", pos=2}
* ...
In both cases you must be really sure, that your given solution is feasible.
